#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Sysogen Lda
#
# Validate commit messages against the Angular commit message guidelines.
#
#   check-commit-message.sh <file>            one message, from a file
#   check-commit-message.sh --range A..B      every commit in a range
#   check-commit-message.sh -                 one message, from stdin
#
# perl is the regex engine because it is present on every macOS and Linux
# developer machine and supports the character classes these patterns need.

set -euo pipefail

readonly TYPES='build|ci|docs|feat|fix|perf|refactor|test'
readonly MAX_HEADER=100
readonly MIN_BODY=20

problems=()

note() {
    problems+=("$1")
}

# Validate one message. Returns 1 if invalid, printing reasons to stderr.
check_message() {
    local message="$1" label="$2"
    local header
    problems=()

    header="$(printf '%s\n' "$message" | head -n 1)"

    # A merge commit is generated by git and is not authored prose.
    if printf '%s' "$header" | perl -ne 'exit(/^Merge /? 0 : 1)'; then
        return 0
    fi

    # Both the Angular revert form and the one git revert generates.
    if printf '%s' "$header" | perl -ne 'exit(/^(revert: |Revert ")/? 0 : 1)'; then
        return 0
    fi

    if printf '%s' "$header" | perl -ne "exit(/^($TYPES)(\\([a-z0-9][a-z0-9._-]*\\))?: /? 0 : 1)"; then
        if [ "${#header}" -gt "$MAX_HEADER" ]; then
            note "header is ${#header} characters, limit is $MAX_HEADER"
        fi

        local summary type second_line body trimmed
        summary="$(printf '%s' "$header" | perl -pe "s/^($TYPES)(\\([^)]*\\))?: //")"

        if [ -z "$summary" ]; then
            note "summary is empty"
        fi
        if printf '%s' "$summary" | perl -ne 'exit(/^[A-Z]/? 0 : 1)'; then
            note "summary must not start with a capital letter"
        fi
        if printf '%s' "$summary" | perl -ne 'exit(/\.$/? 0 : 1)'; then
            note "summary must not end with a full stop"
        fi

        type="$(printf '%s' "$header" | perl -pe 's/[(:].*$//')"
        second_line="$(printf '%s\n' "$message" | sed -n '2p')"
        body="$(printf '%s\n' "$message" | tail -n +3)"

        if [ -n "$second_line" ]; then
            note "the line after the header must be blank"
        fi

        # Angular requires a body on every commit except docs.
        trimmed="$(printf '%s' "$body" | tr -d '[:space:]')"
        if [ "$type" != "docs" ] && [ "${#trimmed}" -lt "$MIN_BODY" ]; then
            note "a '$type' commit needs a body of at least $MIN_BODY characters explaining the motivation"
        fi
    else
        note "header must be '<type>(<optional scope>): <summary>'"
        note "allowed types: ${TYPES//|/, }"
    fi

    if [ "${#problems[@]}" -eq 0 ]; then
        return 0
    fi

    printf '%s\n' "$label" >&2
    printf '  %s\n' "${problems[@]}" >&2
    printf '\n' >&2
    return 1
}

main() {
    local failures=0

    case "${1:-}" in
    --range)
        local range="${2:?--range needs A..B}"
        local shas sha
        # Resolve the range first. A range git cannot parse must be a hard
        # error: silently checking nothing is worse than checking badly.
        if ! shas="$(git rev-list --no-merges "$range" 2>&1)"; then
            printf 'commit message: cannot resolve range %s\n' "$range" >&2
            printf '%s\n' "$shas" >&2
            exit 2
        fi
        while read -r sha; do
            [ -n "$sha" ] || continue
            if ! check_message "$(git log -1 --format=%B "$sha")" \
                "$(git log -1 --format='%h %s' "$sha")"; then
                failures=$((failures + 1))
            fi
        done <<<"$shas"
        ;;
    -)
        check_message "$(cat)" "(stdin)" || failures=1
        ;;
    "")
        printf 'usage: %s <file> | --range A..B | -\n' "$0" >&2
        exit 2
        ;;
    *)
        # Strip comment lines git adds to the editor template.
        check_message "$(perl -ne 'print unless /^#/' "$1")" "$1" || failures=1
        ;;
    esac

    if [ "$failures" -gt 0 ]; then
        printf 'commit message: %d message(s) do not follow the Angular convention.\n' "$failures" >&2
        printf 'See CONTRIBUTING.md, or https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md\n' >&2
        exit 1
    fi
}

main "$@"
