#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Sysogen Lda
#
# Validate commit messages against the Angular commit message guidelines
# combined with the 50/72 subject and body rule. See SKILL.md.
#
#   check-commit-message.sh <file>            one message, from a file
#   check-commit-message.sh --range A..B      every commit in a range
#   check-commit-message.sh -                 one message, from stdin
#   check-commit-message.sh --subject "TEXT"  header rules only, no body rules
#
# perl is the regex engine because it is present on every macOS and Linux
# developer machine and supports the character classes these patterns need.

set -euo pipefail

readonly TYPES='build|ci|docs|feat|fix|perf|refactor|test'
readonly SUBJECT_TARGET=50
readonly SUBJECT_MAX=72
readonly BODY_WRAP=72
readonly MIN_BODY=20

problems=()
advice=()

note() {
    problems+=("$1")
}

# Style targets that are not hard failures: exceeded, they are worth saying,
# but blocking on them would train people to bypass the hook.
suggest() {
    advice+=("$1")
}

# Validate one message. Returns 1 if invalid, printing reasons to stderr.
check_subject() {
    local header="$1" label="${2:-(subject)}"
    problems=()
    advice=()

    if printf '%s' "$header" | perl -ne 'exit(/^(revert: |Revert ")/? 0 : 1)'; then
        return 0
    fi

    if printf '%s' "$header" | perl -ne "exit(/^($TYPES)(\\([a-z0-9][a-z0-9._-]*\\))?: /? 0 : 1)"; then
        if [ "${#header}" -gt "$SUBJECT_MAX" ]; then
            note "subject is ${#header} characters, the maximum is $SUBJECT_MAX"
        elif [ "${#header}" -gt "$SUBJECT_TARGET" ]; then
            suggest "subject is ${#header} characters; aim for $SUBJECT_TARGET"
        fi
        local summary
        summary="$(printf '%s' "$header" | perl -pe "s/^($TYPES)(\\([^)]*\\))?: //")"
        [ -n "$summary" ] || note "summary is empty"
        if printf '%s' "$summary" | perl -ne 'exit(/^[A-Z]/? 0 : 1)'; then
            note "summary must not start with a capital letter"
        fi
        if printf '%s' "$summary" | perl -ne 'exit(/\.$/? 0 : 1)'; then
            note "summary must not end with a full stop"
        fi
    else
        note "must be '<type>(<optional scope>): <summary>'"
        note "allowed types: ${TYPES//|/, }"
    fi

    if [ "${#problems[@]}" -eq 0 ]; then
        [ "${#advice[@]}" -gt 0 ] && printf '  note: %s\n' "${advice[@]}" >&2
        return 0
    fi
    printf '%s\n' "$label" >&2
    printf '  %s\n' "${problems[@]}" >&2
    return 1
}

check_message() {
    local message="$1" label="$2"
    local header
    problems=()
    advice=()

    header="$(printf '%s\n' "$message" | head -n 1)"

    # A merge commit is generated by git and is not authored prose.
    if printf '%s' "$header" | perl -ne 'exit(/^Merge /? 0 : 1)'; then
        return 0
    fi

    # Both the Angular revert form and the one git revert generates.
    if printf '%s' "$header" | perl -ne 'exit(/^(revert: |Revert ")/? 0 : 1)'; then
        return 0
    fi

    if printf '%s' "$header" | perl -ne "exit(/^($TYPES)(\\([a-z0-9][a-z0-9._-]*\\))?: /? 0 : 1)"; then
        if [ "${#header}" -gt "$SUBJECT_MAX" ]; then
            note "subject is ${#header} characters, the maximum is $SUBJECT_MAX"
        elif [ "${#header}" -gt "$SUBJECT_TARGET" ]; then
            suggest "subject is ${#header} characters; aim for $SUBJECT_TARGET so git log --oneline does not truncate it"
        fi

        local summary type second_line body trimmed
        summary="$(printf '%s' "$header" | perl -pe "s/^($TYPES)(\\([^)]*\\))?: //")"

        if [ -z "$summary" ]; then
            note "summary is empty"
        fi
        if printf '%s' "$summary" | perl -ne 'exit(/^[A-Z]/? 0 : 1)'; then
            note "summary must not start with a capital letter"
        fi
        if printf '%s' "$summary" | perl -ne 'exit(/\.$/? 0 : 1)'; then
            note "summary must not end with a full stop"
        fi

        type="$(printf '%s' "$header" | perl -pe 's/[(:].*$//')"
        second_line="$(printf '%s\n' "$message" | sed -n '2p')"
        body="$(printf '%s\n' "$message" | tail -n +3)"

        if [ -n "$second_line" ]; then
            note "the line after the header must be blank"
        fi

        # Angular requires a body on every commit except docs.
        trimmed="$(printf '%s' "$body" | tr -d '[:space:]')"
        if [ "$type" != "docs" ] && [ "${#trimmed}" -lt "$MIN_BODY" ]; then
            note "a '$type' commit needs a body of at least $MIN_BODY characters explaining the motivation"
        fi

        # Wrap advisory. A line with no space is a URL or a path and cannot
        # be wrapped; an indented line is a code block and must not be.
        local long
        long="$(printf '%s\n' "$body" |
            perl -ne "print if length(\$_) - 1 > $BODY_WRAP && /\\S\\s\\S/ && !/^\\s/" |
            wc -l | tr -d ' ')"
        if [ "$long" -gt 0 ]; then
            suggest "$long body line(s) exceed $BODY_WRAP columns"
        fi
    else
        note "header must be '<type>(<optional scope>): <summary>'"
        note "allowed types: ${TYPES//|/, }"
    fi

    if [ "${#problems[@]}" -eq 0 ]; then
        if [ "${#advice[@]}" -gt 0 ]; then
            printf '%s\n' "$label" >&2
            printf '  note: %s\n' "${advice[@]}" >&2
            printf '\n' >&2
        fi
        return 0
    fi

    printf '%s\n' "$label" >&2
    printf '  %s\n' "${problems[@]}" >&2
    if [ "${#advice[@]}" -gt 0 ]; then
        printf '  note: %s\n' "${advice[@]}" >&2
    fi
    printf '\n' >&2
    return 1
}

main() {
    local failures=0

    case "${1:-}" in
    --range)
        local range="${2:?--range needs A..B}"
        local shas sha
        # Resolve the range first. A range git cannot parse must be a hard
        # error: silently checking nothing is worse than checking badly.
        if ! shas="$(git rev-list --no-merges "$range" 2>&1)"; then
            printf 'commit message: cannot resolve range %s\n' "$range" >&2
            printf '%s\n' "$shas" >&2
            exit 2
        fi
        while read -r sha; do
            [ -n "$sha" ] || continue
            if ! check_message "$(git log -1 --format=%B "$sha")" \
                "$(git log -1 --format='%h %s' "$sha")"; then
                failures=$((failures + 1))
            fi
        done <<<"$shas"
        ;;
    --subject)
        check_subject "${2:?--subject needs the text}" "pull request title" || failures=1
        ;;
    -)
        check_message "$(cat)" "(stdin)" || failures=1
        ;;
    "")
        printf 'usage: %s <file> | --range A..B | -\n' "$0" >&2
        exit 2
        ;;
    *)
        # Strip comment lines git adds to the editor template.
        check_message "$(perl -ne 'print unless /^#/' "$1")" "$1" || failures=1
        ;;
    esac

    if [ "$failures" -gt 0 ]; then
        printf 'commit message: %d message(s) do not follow the Angular convention.\n' "$failures" >&2
        printf 'See CONTRIBUTING.md, or https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md\n' >&2
        exit 1
    fi
}

main "$@"
